pipeline {
  agent {
    docker {
      image 'node:17-alpine'
      args '-v $WORKSPACE:/usr/src/app -w /usr/src/app'
    }
  }
  stages {
    stage('Install & Run') {
      steps {
        sh '''
          npm install
          node index.js
        '''
      }
    }
  }
}
